id: IEB7F49B3
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T13:24:05+00:00'
last_modified: '2022-06-10T08:41:01.447083+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00EGS1016947
  title: གསུང་འབུམ། པདྨ་ལུང་རྟོགས་རྒྱ་མཚོ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    4D96:
      image_group_id: I01JW198
      title: Volume 1 of gsung 'bum/_pad+ma lung rtogs rgya mtsho
      total_pages: 534
      order: 1
      base_file: 4D96.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
